import React,{useState} from 'react'
import {ClockPlus} from 'lucide-react'
import {Dialogo} from '@/componentes/ui/dialogo'
import {Boton} from '@/componentes/ui/boton'
import {Entrada} from '@/componentes/ui/entrada'
import {Etiqueta} from '@/componentes/ui/etiqueta'
import {useOperativo} from '@/contextos/contexto-operativo'
import {useAutenticacion} from '@/contextos/contexto-autenticacion'
import type {Turno} from '@/tipos'

const minutosEntre=(inicio:string,fin:string)=>{const [ih,im]=inicio.split(':').map(Number);const [fh,fm]=fin.split(':').map(Number);let a=ih*60+im,b=fh*60+fm;if(b<=a)b+=1440;return b-a}
export const SolicitarHorasExtra:React.FC<{turno:Turno}>=({turno})=>{
 const {solicitarHorasExtra}=useOperativo(); const {usuario}=useAutenticacion(); const [abierto,setAbierto]=useState(false); const [salida,setSalida]=useState(turno.hora_fin); const [motivo,setMotivo]=useState('Reemplazo no llegó'); const [obs,setObs]=useState(''); const [error,setError]=useState(''); const [guardando,setGuardando]=useState(false)
 const enviar=async(e:React.FormEvent)=>{e.preventDefault();setError('');const minutos=minutosEntre(turno.hora_fin,salida);if(minutos<=0){setError('La hora de salida real debe ser posterior a la salida programada.');return};if(!usuario){setError('No hay una sesión activa.');return};setGuardando(true);const r=await solicitarHorasExtra({id_objetivo:turno.id_objetivo,id_vigilador:turno.id_vigilador,id_turno:turno.id,fecha:turno.fecha,hora_salida_programada:turno.hora_fin,hora_salida_real:salida,minutos_solicitados:minutos,motivo,observacion:obs||null});setGuardando(false);if(r){setError(r);return};setAbierto(false);setObs('')}
 return <><Boton variante="primario" tamano="chico" onClick={()=>{setSalida(turno.hora_fin);setError('');setAbierto(true)}} icono={<ClockPlus className="w-4 h-4"/>}>Informar horas extra</Boton><Dialogo abierto={abierto} alCerrar={()=>setAbierto(false)} titulo="Informar horas extra" subtitulo="Las horas quedarán pendientes hasta que la administración las confirme." icono={<ClockPlus className="w-5 h-5 text-amber-500"/>} tamano="medio"><form onSubmit={enviar} className="space-y-4"><div className="grid grid-cols-2 gap-3"><div><Etiqueta>Salida programada</Etiqueta><Entrada type="time" value={turno.hora_fin} readOnly/></div><div><Etiqueta requerido>Salida real</Etiqueta><Entrada type="time" value={salida} onChange={e=>setSalida(e.target.value)}/></div></div><div><Etiqueta requerido>Motivo</Etiqueta><select value={motivo} onChange={e=>setMotivo(e.target.value)} className="w-full min-h-[46px] rounded-xl bg-white dark:bg-[#0A0F1A] border border-slate-300 dark:border-slate-700 px-3 text-sm"><option>Reemplazo no llegó</option><option>Relevo demorado</option><option>Indicación de superior</option><option>Otro</option></select></div><div><Etiqueta>Observación</Etiqueta><textarea value={obs} onChange={e=>setObs(e.target.value)} rows={3} placeholder="Detalle opcional..." className="w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-[#0A0F1A] p-3 text-sm resize-none"/></div>{error&&<p className="text-xs text-red-500 font-semibold">{error}</p>}<div className="flex justify-end gap-2 pt-3 border-t border-slate-200 dark:border-slate-800"><Boton type="button" variante="secundario" onClick={()=>setAbierto(false)}>Cancelar</Boton><Boton type="submit" variante="primario" disabled={guardando}>{guardando?'Enviando...':'Enviar solicitud'}</Boton></div></form></Dialogo></>
}