import React,{createContext,useContext,useEffect,useState} from 'react'
import type { Empresa,Objetivo,Usuario,Asignacion,Turno,NovedadLibro,SolicitudCambio,Aviso,RegistroAuditoria } from '@/tipos'
import { useAutenticacion } from './contexto-autenticacion'
import { supabase } from '@/servicios/supabase'

interface ContextoOperativoTipo {
 empresas:Empresa[]; objetivos:Objetivo[]; vigiladores:Usuario[]; asignaciones:Asignacion[]; turnos:Turno[]; novedades:NovedadLibro[]; solicitudesCambio:SolicitudCambio[]; avisos:Aviso[]; auditorias:RegistroAuditoria[]
 crearEmpresa:(d:{nombre:string;cuit?:string;direccion?:string})=>void; editarEmpresa:(id:string,d:Partial<Empresa>)=>void; eliminarEmpresa:(id:string)=>void
 crearObjetivo:(d:{id_empresa:string;nombre:string;descripcion?:string;direccion:string;localidad:string;provincia:string})=>void; editarObjetivo:(id:string,d:Partial<Objetivo>)=>void; eliminarObjetivo:(id:string)=>void
 crearVigilador:(d:{nombre:string;apellido:string;email:string;telefono?:string;id_empresa:string;id_objetivo_inicial?:string})=>Promise<string|null>; editarVigilador:(id:string,d:Partial<Usuario>)=>void; eliminarVigilador:(id:string)=>void
 trasladarVigilador:(d:{id_vigilador:string;id_nuevo_objetivo:string;fecha_efectiva:string;motivo:string;accion_turnos_futuros:'mantener'|'reasignar'|'cancelar'})=>void
 asignarTurnoGrilla:(d:{id_vigilador:string;id_objetivo:string;fecha:string;codigo:'12☀️'|'12🌙'|'10'|'8'|'F'|'borrar'})=>void
 crearNovedad:(d:{id_objetivo:string;id_vigilador:string;nombre_vigilante:string;nombre_supervisor:string;fecha:string;hora:string;turno:string;elementos_a_cargo:string;informe_novedades:string})=>void; editarNovedad:(id:string,d:{informe_novedades:string;motivo_correccion:string})=>void
 solicitarCambioTurno:(d:{id_solicitante:string;id_destinatario:string;id_turno_origen:string;fecha_turno:string;motivo:string})=>void; responderSolicitudCambio:(id:string,a:boolean)=>void; aprobarCambioAdmin:(id:string,a:boolean)=>void
 crearAviso:(d:{titulo:string;contenido:string;prioridad:Aviso['prioridad']})=>void; marcarAvisoLeido:(id:string)=>void
}
const ContextoOperativo=createContext<ContextoOperativoTipo|undefined>(undefined)

export const ProveedorOperativo:React.FC<{children:React.ReactNode}>=({children})=>{
const {usuario}=useAutenticacion()
const [empresas,setEmpresas]=useState<Empresa[]>([]),[objetivos,setObjetivos]=useState<Objetivo[]>([]),[vigiladores,setVigiladores]=useState<Usuario[]>([])
const [asignaciones,setAsignaciones]=useState<Asignacion[]>([]),[turnos,setTurnos]=useState<Turno[]>([]),[novedades,setNovedades]=useState<NovedadLibro[]>([])
const [solicitudesCambio,setSolicitudesCambio]=useState<SolicitudCambio[]>([]),[avisos,setAvisos]=useState<Aviso[]>([]),[auditorias,setAuditorias]=useState<RegistroAuditoria[]>([])
const cargar=async()=>{
 if(!supabase||!usuario)return; const eid=usuario.id_empresa
 try{
  const [er,or,pr,vr,ar,tr,nr,sr,avr,aur,lr]=await Promise.all([
   usuario.rol==='super_administrador'?supabase.from('empresas').select('*').order('nombre'):eid?supabase.from('empresas').select('*').eq('id',eid).order('nombre'):supabase.from('empresas').select('*').limit(0),
   supabase.from('objetivos').select('*').order('nombre'),supabase.from('perfiles').select('id,id_empresa,nombre,apellido,telefono,rol,activo,debe_cambiar_contrasena,creado_en'),supabase.from('vigiladores').select('*').order('apellido'),
   supabase.from('asignaciones').select('*').order('fecha_inicio',{ascending:false}),supabase.from('turnos').select('*').order('fecha'),supabase.from('novedades_libro').select('*').order('fecha',{ascending:false}).order('hora',{ascending:false}),
   supabase.from('solicitudes_cambio').select('*').order('creado_en',{ascending:false}),supabase.from('avisos').select('*').order('creado_en',{ascending:false}),supabase.from('auditoria').select('*').order('fecha_hora',{ascending:false}),supabase.from('avisos_lecturas').select('id_aviso').eq('id_usuario',usuario.id)
  ]); const err=[er,or,pr,vr,ar,tr,nr,sr,avr,aur,lr].find(x=>x.error)?.error;if(err)throw err
  const E=er.data||[],O=or.data||[],P=pr.data||[],V=vr.data||[],read=new Set((lr.data||[]).map(x=>x.id_aviso)),em=new Map(E.map(x=>[x.id,x.nombre])),om=new Map(O.map(x=>[x.id,x.nombre])),pm=new Map(P.map(x=>[x.id,x])),uByV=new Map(V.filter(x=>x.id_usuario).map(x=>[x.id,x.id_usuario]))
  const visible=(id:string|null|undefined)=>usuario.rol==='super_administrador'||id===eid
  setEmpresas(E.map(x=>({id:x.id,nombre:x.nombre,cuit:x.cuit||'',direccion:x.direccion||'',activa:x.activa,creada_en:x.creada_en})))
  setObjetivos(O.filter(x=>visible(x.id_empresa)).map(x=>({id:x.id,id_empresa:x.id_empresa,nombre:x.nombre,descripcion:x.descripcion||'',direccion:x.direccion||'',localidad:x.localidad||'',provincia:x.provincia||'',activo:x.activo,creado_en:x.creado_en})))
  setVigiladores(V.filter(x=>visible(x.id_empresa)).map(x=>{const p=x.id_usuario?pm.get(x.id_usuario):null;if(!p||p.rol!=='vigilador')return null;return{id:p.id,email:'',nombre:p.nombre,apellido:p.apellido,rol:p.rol,id_empresa:p.id_empresa,empresa_nombre:p.id_empresa?em.get(p.id_empresa)||null:null,telefono:p.telefono||null,activo:!!(p.activo&&x.activo),debe_cambiar_contrasena:!!p.debe_cambiar_contrasena,creado_en:p.creado_en} as Usuario}).filter(Boolean) as Usuario[])
  setAsignaciones((ar.data||[]).filter(x=>visible(x.id_empresa)).map(x=>({id:x.id,id_vigilador:uByV.get(x.id_vigilador)||x.id_vigilador,id_objetivo:x.id_objetivo,objetivo_nombre:om.get(x.id_objetivo),fecha_inicio:x.fecha_inicio,fecha_fin:x.fecha_fin,activa:x.activa,motivo_traslado:x.motivo_traslado,creado_por:x.creado_por||'',creado_en:x.creado_en})))
  setTurnos((tr.data||[]).filter(x=>visible(x.id_empresa)).map(x=>({id:x.id,id_empresa:x.id_empresa,id_objetivo:x.id_objetivo,id_vigilador:uByV.get(x.id_vigilador)||x.id_vigilador,fecha:x.fecha,hora_inicio:x.hora_inicio||'00:00',hora_fin:x.hora_fin||'00:00',horas_totales:Number(x.horas_totales||0),tipo:x.tipo,horas_diurnas:Number(x.horas_diurnas||0),horas_nocturnas:Number(x.horas_nocturnas||0),es_feriado:!!x.es_feriado,es_domingo:!!x.es_domingo,horas_extra:Number(x.horas_extra||0),estado:x.estado})))
  setNovedades((nr.data||[]).filter(x=>visible(x.id_empresa)).map(x=>({id:x.id,id_empresa:x.id_empresa,id_objetivo:x.id_objetivo,id_vigilador:x.id_vigilador||'',nombre_vigilante:x.nombre_vigilante,nombre_supervisor:x.nombre_supervisor||'',fecha:x.fecha,hora:x.hora,turno:x.turno||'',elementos_a_cargo:x.elementos_a_cargo||'',informe_novedades:x.informe_novedades,creado_en:x.creado_en})))
  setSolicitudesCambio((sr.data||[]).filter(x=>visible(x.id_empresa)).map(x=>({id:x.id,id_empresa:x.id_empresa,id_solicitante:x.id_solicitante,id_destinatario:x.id_destinatario||'',id_turno_origen:x.id_turno_origen,fecha_turno:x.fecha_turno,estado:x.estado,motivo:x.motivo||'',creado_en:x.creado_en})))
  setAvisos((avr.data||[]).filter(x=>visible(x.id_empresa)).map(x=>{const p=x.autor_id?pm.get(x.autor_id):null;return{id:x.id,id_empresa:x.id_empresa,autor_nombre:p?p.nombre+' '+p.apellido:'Administración',titulo:x.titulo,contenido:x.contenido,prioridad:x.prioridad,leido:read.has(x.id),creado_en:x.creado_en}}))
  setAuditorias((aur.data||[]).filter(x=>visible(x.id_empresa)).map(x=>{const p=x.id_usuario?pm.get(x.id_usuario):null;return{id:x.id,id_usuario:x.id_usuario||'',usuario_nombre:p?p.nombre+' '+p.apellido:'Sistema',accion:x.accion,entidad:x.entidad,detalle:typeof x.detalle==='string'?x.detalle:JSON.stringify(x.detalle||{}),fecha_hora:x.fecha_hora}}))
 }catch(e){console.error('Error cargando datos operativos:',e)}
}
useEffect(()=>{void cargar()},[usuario])
const audit=async(a:string,e:string,d:string,id?:string,empresa?:string|null)=>{if(!supabase||!usuario)return;const r=await supabase.from('auditoria').insert({id_empresa:empresa??usuario.id_empresa??null,id_usuario:usuario.id,accion:a,entidad:e,entidad_id:id??null,detalle:{texto:d}}).select('*').single();if(r.error){console.error(r.error);return}setAuditorias(p=>[{id:r.data.id,id_usuario:usuario.id,usuario_nombre:usuario.nombre+' '+usuario.apellido,accion:r.data.accion,entidad:r.data.entidad,detalle:d,fecha_hora:r.data.fecha_hora},...p])}
const crearEmpresa=(d:{nombre:string;cuit?:string;direccion?:string})=>{void(async()=>{if(!supabase)return;const r=await supabase.from('empresas').insert({nombre:d.nombre,cuit:d.cuit||null,direccion:d.direccion||null}).select('*').single();if(r.error){console.error(r.error);return}setEmpresas(p=>[r.data as Empresa,...p]);await audit('CREAR_EMPRESA','Empresa','Creó la empresa '+d.nombre,r.data.id,r.data.id)})()}
const editarEmpresa=(id:string,d:Partial<Empresa>)=>{void(async()=>{if(!supabase)return;const r=await supabase.from('empresas').update(d).eq('id',id).select('*').single();if(r.error){console.error(r.error);return}setEmpresas(p=>p.map(x=>x.id===id?r.data as Empresa:x));await audit('EDITAR_EMPRESA','Empresa','Modificó empresa '+id,id)})()}
const eliminarEmpresa=(id:string)=>{void(async()=>{if(!supabase)return;const r=await supabase.from('empresas').update({activa:false}).eq('id',id);if(r.error){console.error(r.error);return}setEmpresas(p=>p.map(x=>x.id===id?{...x,activa:false}:x));await audit('ELIMINAR_EMPRESA','Empresa','Desactivó empresa '+id,id)})()}
const crearObjetivo=(d:{id_empresa:string;nombre:string;descripcion?:string;direccion:string;localidad:string;provincia:string})=>{void(async()=>{if(!supabase)return;const r=await supabase.from('objetivos').insert({...d,descripcion:d.descripcion||null,activo:true}).select('*').single();if(r.error){console.error(r.error);return}setObjetivos(p=>[r.data as Objetivo,...p]);await audit('CREAR_OBJETIVO','Objetivo','Creó objetivo '+d.nombre,r.data.id,d.id_empresa)})()}
const editarObjetivo=(id:string,d:Partial<Objetivo>)=>{void(async()=>{if(!supabase)return;const r=await supabase.from('objetivos').update(d).eq('id',id).select('*').single();if(r.error){console.error(r.error);return}setObjetivos(p=>p.map(x=>x.id===id?r.data as Objetivo:x));await audit('EDITAR_OBJETIVO','Objetivo','Modificó objetivo '+id,id,r.data.id_empresa)})()}
const eliminarObjetivo=(id:string)=>{void(async()=>{if(!supabase)return;const o=objetivos.find(x=>x.id===id),r=await supabase.from('objetivos').update({activo:false}).eq('id',id);if(r.error){console.error(r.error);return}setObjetivos(p=>p.map(x=>x.id===id?{...x,activo:false}:x));await audit('ELIMINAR_OBJETIVO','Objetivo','Desactivó objetivo '+id,id,o?.id_empresa)})()}
const crearVigilador=async(d:{nombre:string;apellido:string;email:string;telefono?:string;id_empresa:string;id_objetivo_inicial?:string})=>{if(!supabase)return 'Supabase no está configurado.';try{const r=await supabase.functions.invoke('crear-vigilador',{body:d});if(r.error){console.error(r.error);return r.error.message||'No se pudo crear el vigilador.'}if(r.data?.error){console.error(r.data.error);return String(r.data.error)}await cargar();return null}catch(error){console.error(error);return error instanceof Error?error.message:'Error inesperado al crear el vigilador.'}}
const editarVigilador=(id:string,d:Partial<Usuario>)=>{void(async()=>{if(!supabase)return;const v=vigiladores.find(x=>x.id===id);if(!v)return;const p=await supabase.from('perfiles').update({...(d.nombre!==undefined?{nombre:d.nombre}:{}),...(d.apellido!==undefined?{apellido:d.apellido}:{}),...(d.telefono!==undefined?{telefono:d.telefono||null}:{}),...(d.activo!==undefined?{activo:d.activo}:{}),...(d.id_empresa!==undefined?{id_empresa:d.id_empresa||null}:{})}).eq('id',id);if(p.error){console.error(p.error);return}const db=await supabase.from('vigiladores').select('id').eq('id_usuario',id).maybeSingle();if(db.error){console.error(db.error);return}if(db.data){const q=await supabase.from('vigiladores').update({...(d.nombre!==undefined?{nombre:d.nombre}:{}),...(d.apellido!==undefined?{apellido:d.apellido}:{}),...(d.telefono!==undefined?{telefono:d.telefono||null}:{}),...(d.activo!==undefined?{activo:d.activo}:{}),...(d.id_empresa!==undefined?{id_empresa:d.id_empresa}:{})}).eq('id',db.data.id);if(q.error){console.error(q.error);return}}setVigiladores(p=>p.map(x=>x.id===id?{...x,...d}:x));await audit('EDITAR_VIGILADOR','Vigilador','Modificó datos de '+v.nombre+' '+v.apellido,id,v.id_empresa)})()}
const eliminarVigilador=(id:string)=>{void(async()=>{if(!supabase)return;const v=vigiladores.find(x=>x.id===id);if(!v)return;const db=await supabase.from('vigiladores').select('id').eq('id_usuario',id).maybeSingle();if(db.error){console.error(db.error);return}const p=await supabase.from('perfiles').update({activo:false}).eq('id',id);if(p.error){console.error(p.error);return}if(db.data){const q=await supabase.from('vigiladores').update({activo:false}).eq('id',db.data.id);if(q.error){console.error(q.error);return}}setVigiladores(p=>p.map(x=>x.id===id?{...x,activo:false}:x));await audit('ELIMINAR_VIGILADOR','Vigilador','Desactivó a '+v.nombre+' '+v.apellido,id,v.id_empresa)})()}
const trasladarVigilador=(d:{id_vigilador:string;id_nuevo_objetivo:string;fecha_efectiva:string;motivo:string;accion_turnos_futuros:'mantener'|'reasignar'|'cancelar'})=>{void(async()=>{if(!supabase||!usuario)return;const v=vigiladores.find(x=>x.id===d.id_vigilador),o=objetivos.find(x=>x.id===d.id_nuevo_objetivo);if(!v||!o)return;const db=await supabase.from('vigiladores').select('id,id_empresa').eq('id_usuario',d.id_vigilador).maybeSingle();if(db.error||!db.data)return;const old=await supabase.from('asignaciones').select('id').eq('id_vigilador',db.data.id).eq('activa',true).maybeSingle();if(old.data)await supabase.from('asignaciones').update({activa:false,fecha_fin:d.fecha_efectiva}).eq('id',old.data.id);const ins=await supabase.from('asignaciones').insert({id_empresa:db.data.id_empresa,id_vigilador:db.data.id,id_objetivo:o.id,fecha_inicio:d.fecha_efectiva,activa:true,motivo_traslado:d.motivo,creado_por:usuario.id}).select('*').single();if(ins.error){console.error(ins.error);return}if(d.accion_turnos_futuros==='reasignar')await supabase.from('turnos').update({id_objetivo:o.id}).eq('id_vigilador',db.data.id).gte('fecha',d.fecha_efectiva);if(d.accion_turnos_futuros==='cancelar')await supabase.from('turnos').delete().eq('id_vigilador',db.data.id).gte('fecha',d.fecha_efectiva);await audit('TRASLADO_VIGILADOR','Asignacion','Trasladó a '+v.nombre+' '+v.apellido+' a '+o.nombre+'. Motivo: '+d.motivo,ins.data.id,db.data.id_empresa);await cargar()})()}
const asignarTurnoGrilla=(d:{id_vigilador:string;id_objetivo:string;fecha:string;codigo:'12☀️'|'12🌙'|'10'|'8'|'F'|'borrar'})=>{void(async()=>{if(!supabase)return;const db=await supabase.from('vigiladores').select('id,id_empresa').eq('id_usuario',d.id_vigilador).maybeSingle();if(db.error||!db.data)return;if(d.codigo==='borrar'){const r=await supabase.from('turnos').delete().eq('id_vigilador',db.data.id).eq('fecha',d.fecha);if(r.error){console.error(r.error);return}setTurnos(p=>p.filter(x=>!(x.id_vigilador===d.id_vigilador&&x.fecha===d.fecha)));return}const [y,m,day]=d.fecha.split('-').map(Number),date=new Date(y,m-1,day),fer=await supabase.from('feriados').select('fecha').eq('fecha',d.fecha).or('id_empresa.is.null,id_empresa.eq.'+db.data.id_empresa);let h=12,t:Turno['tipo']='diurno',ini='07:00',fin='19:00',di=12,no=0;if(d.codigo==='12🌙'){t='nocturno';ini='19:00';fin='07:00';di=3;no=9}else if(d.codigo==='10'){t='especial';h=10;ini='08:00';fin='18:00'}else if(d.codigo==='8'){h=8;ini='08:00';fin='16:00';di=8}else if(d.codigo==='F'){t='franco';h=0;ini='00:00';fin='00:00';di=0}const ex=turnos.find(x=>x.id_vigilador===d.id_vigilador&&x.fecha===d.fecha),payload={id_empresa:db.data.id_empresa,id_objetivo:d.id_objetivo,id_vigilador:db.data.id,fecha:d.fecha,hora_inicio:ini,hora_fin:fin,horas_totales:h,tipo:t,horas_diurnas:di,horas_nocturnas:no,es_feriado:!!fer.data?.length,es_domingo:date.getDay()===0,horas_extra:0,estado:'programado'};const r=ex?await supabase.from('turnos').update(payload).eq('id',ex.id).select('*').single():await supabase.from('turnos').insert(payload).select('*').single();if(r.error){console.error(r.error);return}await cargar()})()}
const crearNovedad=(d:{id_objetivo:string;id_vigilador:string;nombre_vigilante:string;nombre_supervisor:string;fecha:string;hora:string;turno:string;elementos_a_cargo:string;informe_novedades:string})=>{void(async()=>{if(!supabase||!usuario)return;const v=vigiladores.find(x=>x.id===d.id_vigilador),db=await supabase.from('vigiladores').select('id').eq('id_usuario',d.id_vigilador).maybeSingle();if(!v?.id_empresa||db.error||!db.data)return;const r=await supabase.from('novedades_libro').insert({id_empresa:v.id_empresa,id_objetivo:d.id_objetivo,id_vigilador:db.data.id,nombre_vigilante:d.nombre_vigilante,nombre_supervisor:d.nombre_supervisor||null,fecha:d.fecha,hora:d.hora,turno:d.turno||null,elementos_a_cargo:d.elementos_a_cargo||null,informe_novedades:d.informe_novedades,creado_por:usuario.id}).select('*').single();if(r.error){console.error(r.error);return}await audit('LIBRO_NOVEDADES','Novedad','Asentó una novedad',r.data.id,r.data.id_empresa);await cargar()})()}
const editarNovedad=(id:string,d:{informe_novedades:string;motivo_correccion:string})=>{void(async()=>{if(!supabase||!usuario)return;const n=novedades.find(x=>x.id===id);if(!n)return;const r=await supabase.from('novedades_correcciones').insert({id_novedad:id,id_empresa:n.id_empresa,correccion:d.informe_novedades,motivo:d.motivo_correccion,corregido_por:usuario.id}).select('*').single();if(r.error){console.error(r.error);return}await audit('CORRECCION_NOVEDAD','Novedad','Registró corrección: '+d.motivo_correccion,r.data.id,n.id_empresa);await cargar()})()}
const solicitarCambioTurno=(d:{id_solicitante:string;id_destinatario:string;id_turno_origen:string;fecha_turno:string;motivo:string})=>{void(async()=>{if(!supabase||!usuario?.id_empresa)return;const r=await supabase.from('solicitudes_cambio').insert({id_empresa:usuario.id_empresa,id_solicitante:d.id_solicitante,id_destinatario:d.id_destinatario||null,id_turno_origen:d.id_turno_origen,fecha_turno:d.fecha_turno,estado:'pendiente',motivo:d.motivo||null}).select('*').single();if(r.error){console.error(r.error);return}await audit('SOLICITUD_CAMBIO','Turno','Creó solicitud para '+d.fecha_turno,r.data.id,r.data.id_empresa);await cargar()})()}
const responderSolicitudCambio=(id:string,a:boolean)=>{void(async()=>{if(!supabase)return;const r=await supabase.from('solicitudes_cambio').update({estado:a?'aceptada_vigilador':'rechazada_vigilador'}).eq('id',id);if(r.error)console.error(r.error);else await cargar()})()}
const aprobarCambioAdmin=(id:string,a:boolean)=>{void(async()=>{if(!supabase)return;const s=solicitudesCambio.find(x=>x.id===id);if(!s)return;if(!a){await supabase.from('solicitudes_cambio').update({estado:'cancelada'}).eq('id',id);await cargar();return}const db=await supabase.from('vigiladores').select('id').eq('id_usuario',s.id_destinatario).maybeSingle();if(db.error||!db.data)return;const tr=await supabase.from('turnos').update({id_vigilador:db.data.id,estado:'reemplazado'}).eq('id',s.id_turno_origen);if(tr.error){console.error(tr.error);return}await supabase.from('solicitudes_cambio').update({estado:'aprobada_admin'}).eq('id',id);await audit('APROBACION_CAMBIO_TURNO','Turno','Aprobó cambio para '+s.fecha_turno,s.id_turno_origen,s.id_empresa);await cargar()})()}
const crearAviso=(d:{titulo:string;contenido:string;prioridad:Aviso['prioridad']})=>{void(async()=>{if(!supabase||!usuario?.id_empresa)return;const r=await supabase.from('avisos').insert({id_empresa:usuario.id_empresa,autor_id:usuario.id,titulo:d.titulo,contenido:d.contenido,prioridad:d.prioridad}).select('*').single();if(r.error){console.error(r.error);return}await audit('CREAR_AVISO','Aviso','Publicó aviso: '+d.titulo,r.data.id,r.data.id_empresa);await cargar()})()}
const marcarAvisoLeido=(id:string)=>{void(async()=>{if(!supabase||!usuario)return;const r=await supabase.from('avisos_lecturas').upsert({id_aviso:id,id_usuario:usuario.id},{onConflict:'id_aviso,id_usuario'});if(r.error){console.error(r.error);return}setAvisos(p=>p.map(x=>x.id===id?{...x,leido:true}:x))})()}
return <ContextoOperativo.Provider value={{empresas,objetivos,vigiladores,asignaciones,turnos,novedades,solicitudesCambio,avisos,auditorias,crearEmpresa,editarEmpresa,eliminarEmpresa,crearObjetivo,editarObjetivo,eliminarObjetivo,crearVigilador,editarVigilador,eliminarVigilador,trasladarVigilador,asignarTurnoGrilla,crearNovedad,editarNovedad,solicitarCambioTurno,responderSolicitudCambio,aprobarCambioAdmin,crearAviso,marcarAvisoLeido}}>{children}</ContextoOperativo.Provider>
}
export function useOperativo():ContextoOperativoTipo{const c=useContext(ContextoOperativo);if(!c)throw new Error('useOperativo debe utilizarse dentro de ProveedorOperativo');return c}